using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Cimai.Generators;

[Generator]
public class NativeWrapperGenerator : IIncrementalGenerator
{
    // 小型 POD：生成 readonly 值 struct，_native 是值字段，零开销。
    private static readonly string[] VALUE_STRUCT_TYPES =
        ["SimaiNote", "SimaiTiming", "SimaiCommand"];

    // 带非托管资源：生成 sealed unsafe class，_native 是 Native.X* 指针字段，
    // accessor 走 -> 解引用，由 wrapper partial 负责 Parse/Dispose/finalizer。
    private static readonly string[] REFERENCE_CLASS_TYPES =
        ["SimaiChart", "SimaiFile"];

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 所有属于 Cimai.Native 的类型定义
        IncrementalValuesProvider<INamedTypeSymbol> nativeSymbols = context.CompilationProvider
            .SelectMany(static (compilation, _) =>
            {
                var nativeNamespace = compilation.GlobalNamespace
                    .GetNamespaceMembers()
                    .FirstOrDefault(n => n.Name == "Cimai")
                    ?
                    .GetNamespaceMembers()
                    .FirstOrDefault(n => n.Name == "Native");

                if (nativeNamespace is null)
                    return Enumerable.Empty<INamedTypeSymbol>();

                return nativeNamespace.GetTypeMembers();
            });

        // 注册源码生成输出
        context.RegisterSourceOutput(nativeSymbols, static (spc, symbol) =>
        {
            if (symbol is null)
                return;

            // ---- Enum 复制生成到 Cimai 命名空间下 ----
            if (symbol.TypeKind == TypeKind.Enum)
            {
                var enumCode = GenerateEnum(symbol);
                spc.AddSource($"{symbol.Name}.g.cs", enumCode);
                return;
            }

            if (symbol.TypeKind != TypeKind.Struct)
                return;

            // ---- 值 struct 路径 ----
            if (VALUE_STRUCT_TYPES.Contains(symbol.Name))
            {
                var structCode = GenerateValueStructWrapper(symbol);
                spc.AddSource($"{symbol.Name}.g.cs", structCode);
            }
            // ---- reference class 路径 ----
            else if (REFERENCE_CLASS_TYPES.Contains(symbol.Name))
            {
                spc.AddSource($"{symbol.Name}.g.cs", GenerateReferenceClassWrapper(symbol));
            }
        });
    }

    // 生成 Enum 副本
    private static string GenerateEnum(INamedTypeSymbol enumSymbol)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("namespace Cimai;");
        sb.AppendLine();

        // 获取底层类型 (如 int, uint 等)
        var underlyingType = enumSymbol.EnumUnderlyingType?.ToDisplayString() ?? "int";
        sb.AppendLine($"public enum {enumSymbol.Name} : {underlyingType}");
        sb.AppendLine("{");

        // 遍历枚举的所有成员项及对应数值
        foreach (var member in enumSymbol.GetMembers().OfType<IFieldSymbol>())
        {
            if (member.HasConstantValue)
            {
                sb.AppendLine($"    {member.Name} = {member.ConstantValue},");
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // 生成 值 struct 包装器（POD 类型，_native 是值字段）
    private static string GenerateValueStructWrapper(INamedTypeSymbol structSymbol)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using Cimai.Native;");
        sb.AppendLine();
        sb.AppendLine("namespace Cimai;");
        sb.AppendLine();

        var fullName = structSymbol.ToDisplayString(); // 如 Cimai.Native.SimaiNote

        sb.AppendLine("[StructLayout(LayoutKind.Sequential)]");
        sb.AppendLine($"public readonly partial struct {structSymbol.Name}");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly {fullName} _native;");
        sb.AppendLine();
        sb.AppendLine($"    public {structSymbol.Name}({fullName} native) => _native = native;");
        sb.AppendLine($"    public static implicit operator {structSymbol.Name}({fullName} native) => new(native);");
        sb.AppendLine($"    public static implicit operator {fullName}({structSymbol.Name} wrapper) => wrapper._native;");
        sb.AppendLine();

        // 遍历结构体实例字段
        foreach (var field in structSymbol.GetMembers().OfType<IFieldSymbol>())
        {
            if (field.IsStatic) continue;

            var origName = field.Name;
            var pascName = ToPascalCaseName(origName);
            var fieldType = field.Type;

            // ======ban list======

            // SimaiTiming.Content 是一个指向解析内容的 String_View，不保证在 Wrapper 生命周期内有效。
            if (structSymbol.Name == "SimaiTiming" && pascName == "Content")
            {
                continue;
            }
            // 所有 Arena 都不应被 public
            else if (pascName == "Arena")
            {
                continue;
            }


            // ======special types======

            // Enum
            else if (fieldType.TypeKind == TypeKind.Enum)
            {
                var enumName = fieldType.Name;
                sb.AppendLine($"    public {enumName} {pascName} => ({enumName})_native.{origName};");
            }
            // xxxList
            else if (fieldType.Name.EndsWith("List"))
            {
                var elemType = fieldType.Name.Substring(0, fieldType.Name.Length - 4);

                // 使用 unsafe ReadOnlySpan 提取内部 items 指针与 count 计数
                sb.AppendLine($"    public unsafe ReadOnlySpan<{elemType}> {pascName} =>");
                sb.AppendLine($"        new(_native.{origName}.items, checked((int)_native.{origName}.count));");
            }
            // String_View
            else if (fieldType.Name == "String_View")
            {
                sb.AppendLine($"    public unsafe ReadOnlySpan<byte> {pascName} => ");
                sb.AppendLine($"        new(_native.{origName}.data, checked((int)_native.{origName}.count));");
            }
            // _Bool / bool
            else if (GetNativeType(field) is string nativeType && (nativeType == "_Bool" || nativeType == "bool"))
            {
                sb.AppendLine($"    public bool {pascName} => _native.{origName} != 0;");
            }


            // ======others======

            else
            {
                sb.AppendLine($"    public {fieldType.ToDisplayString()} {pascName} => _native.{origName};");
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // REFERENCE_CLASS_TYPES 类型对应的 C 端 release 函数名（命名约定：cimai_{type}_release）
    private static readonly Dictionary<string, string> RELEASE_FUNCTIONS = new()
    {
        ["SimaiChart"] = "cimai_chart_release",
        ["SimaiFile"] = "cimai_file_release",
    };

    private static string GenerateReferenceClassWrapper(INamedTypeSymbol structSymbol)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using Cimai.Native;");
        sb.AppendLine();
        sb.AppendLine("namespace Cimai;");
        sb.AppendLine();

        var typeName = structSymbol.Name;
        var fullName = structSymbol.ToDisplayString(); // e.g., Cimai.Native.SimaiChart
        var releaseFunc = RELEASE_FUNCTIONS[typeName];

        sb.AppendLine($"public sealed unsafe partial class {typeName} : IDisposable");
        sb.AppendLine("{");
        // 值字段，非 readonly：Dispose 把 _native 整体清零，确保里面的指针字段（timings.items / _arena 等）
        // 都是 NULL，多次 Dispose 幂等。_native 本身跟着 GC 走，class 实例被回收时它一起被回收。
        sb.AppendLine($"    private {fullName} _native;");
        sb.AppendLine();

        foreach (var field in structSymbol.GetMembers().OfType<IFieldSymbol>())
        {
            if (field.IsStatic) continue;

            var origName = field.Name;
            var pascName = ToPascalCaseName(origName);
            var fieldType = field.Type;

            // ======ban list======

            // SimaiTiming.Content 是一个指向解析内容的 String_View，不保证在 Wrapper 生命周期内有效。
            if (structSymbol.Name == "SimaiTiming" && pascName == "Content")
                continue;
            // 所有 Arena 都不应被 public。
            if (pascName == "Arena")
                continue;


            // ======special types======

            // Enum
            if (fieldType.TypeKind == TypeKind.Enum)
            {
                var enumName = fieldType.Name;
                sb.AppendLine($"    public {enumName} {pascName} => ({enumName})_native.{origName};");
            }
            // xxxList
            else if (fieldType.Name.EndsWith("List"))
            {
                var elemType = fieldType.Name.Substring(0, fieldType.Name.Length - 4);

                // 使用 unsafe ReadOnlySpan 提取内部 items 指针与 count 计数
                sb.AppendLine($"    public unsafe ReadOnlySpan<{elemType}> {pascName} =>");
                sb.AppendLine($"        new(_native.{origName}.items, checked((int)_native.{origName}.count));");
            }
            // String_View
            else if (fieldType.Name == "String_View")
            {
                sb.AppendLine($"    public unsafe ReadOnlySpan<byte> {pascName} => ");
                sb.AppendLine($"        new(_native.{origName}.data, checked((int)_native.{origName}.count));");
            }
            // _Bool / bool
            else if (GetNativeType(field) is string nativeType && (nativeType == "_Bool" || nativeType == "bool"))
            {
                sb.AppendLine($"    public bool {pascName} => _native.{origName} != 0;");
            }


            // ======others======

            else
            {
                sb.AppendLine($"    public {fieldType.ToDisplayString()} {pascName} => _native.{origName};");
            }
        }

        // ---- 生命周期模板：所有 reference class 走同一条路 ----
        sb.AppendLine();
        sb.AppendLine("    private void Free()");
        sb.AppendLine("    {");
        sb.AppendLine($"        fixed ({fullName}* p = &_native)");
        sb.AppendLine("        {");
        sb.AppendLine($"            Native.Methods.{releaseFunc}(p);");
        sb.AppendLine("        }");
        sb.AppendLine("        _native = default;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public void Dispose()");
        sb.AppendLine("    {");
        sb.AppendLine("        Free();");
        sb.AppendLine("        GC.SuppressFinalize(this);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    ~{typeName}() => Free();");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string ToPascalCaseName(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        if (NameMap.TryGetValue(name, out var mappedName)) return mappedName;

        var parts = name.Split(['_'], StringSplitOptions.RemoveEmptyEntries);
        for (int i = 0; i < parts.Length; i++)
        {
            if (parts[i].Length > 0)
                parts[i] = char.ToUpper(parts[i][0]) + parts[i].Substring(1);
        }
        return string.Concat(parts);
    }

    private static readonly Dictionary<string, string> NameMap = new()
    {
        { "hspeed", "HSpeed" },
        { "sveloc", "SVeloc" },
    };

    private static string GetNativeType(IFieldSymbol field)
    {
        foreach (var attr in field.GetAttributes())
        {
            if (attr.AttributeClass?.Name == "NativeTypeNameAttribute" ||
                attr.AttributeClass?.Name == "NativeTypeName")
            {
                if (attr.ConstructorArguments.Length > 0 &&
                    attr.ConstructorArguments[0].Value is string typeName)
                {
                    return typeName;
                }
            }
        }
        return string.Empty;
    }
}