using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Cimai.Generators;

[Generator]
public class NativeWrapperGenerator : IIncrementalGenerator
{
    private static readonly string[] STRUCT_WHITELIST = ["SimaiNote", "SimaiTiming", "SimaiChart", "SimaiFile", "SimaiCommand"];
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 所有属于 Cimai.Native 的类型定义
        IncrementalValuesProvider<INamedTypeSymbol> nativeSymbols = context.CompilationProvider
            .SelectMany(static (compilation, _) =>
            {
                var nativeNamespace = compilation.GlobalNamespace
                    .GetNamespaceMembers()
                    .FirstOrDefault(n => n.Name == "Cimai")
                    ?
                    .GetNamespaceMembers()
                    .FirstOrDefault(n => n.Name == "Native");

                if (nativeNamespace is null)
                    return Enumerable.Empty<INamedTypeSymbol>();

                return nativeNamespace.GetTypeMembers();
            });

        // 注册源码生成输出
        context.RegisterSourceOutput(nativeSymbols, static (spc, symbol) =>
        {
            if (symbol is null)
                return;

            // ---- Enum 复制生成到 Cimai 命名空间下 ----
            if (symbol.TypeKind == TypeKind.Enum)
            {
                var enumCode = GenerateEnum(symbol);
                spc.AddSource($"{symbol.Name}.g.cs", enumCode);
                return;
            }

            // ---- Struct 白名单 ----
            if (symbol.TypeKind == TypeKind.Struct)
            {
                if (!STRUCT_WHITELIST.Contains(symbol.Name))
                    return;

                var (structCode, fixedBufferWrappers) = GenerateStructWrapper(symbol);
                spc.AddSource($"{symbol.Name}.g.cs", structCode);

                // 内联数组字段的包装类型作为单独 partial 文件输出，避免与属性同名冲突。
                foreach (var fb in fixedBufferWrappers)
                {
                    spc.AddSource($"{symbol.Name}.{fb.CollectionName}.g.cs", GenerateFixedBufferWrapper(symbol.Name, fb));
                }
            }
        });
    }

    // 生成 Enum 副本
    private static string GenerateEnum(INamedTypeSymbol enumSymbol)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("namespace Cimai;");
        sb.AppendLine();

        // 获取底层类型 (如 int, uint 等)
        var underlyingType = enumSymbol.EnumUnderlyingType?.ToDisplayString() ?? "int";
        sb.AppendLine($"public enum {enumSymbol.Name} : {underlyingType}");
        sb.AppendLine("{");

        // 遍历枚举的所有成员项及对应数值
        foreach (var member in enumSymbol.GetMembers().OfType<IFieldSymbol>())
        {
            if (member.HasConstantValue)
            {
                sb.AppendLine($"    {member.Name} = {member.ConstantValue},");
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // 生成 Struct 包装器
    private static (string StructCode, List<FixedBufferWrapper> FixedBuffers) GenerateStructWrapper(INamedTypeSymbol structSymbol)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using Cimai.Native;");
        sb.AppendLine();
        sb.AppendLine("namespace Cimai;");
        sb.AppendLine();

        var fixedBufferWrappers = new List<FixedBufferWrapper>();
        var fullName = structSymbol.ToDisplayString(); // 如 Cimai.Native.SimaiNote

        sb.AppendLine("[StructLayout(LayoutKind.Sequential)]");
        sb.AppendLine($"public readonly partial struct {structSymbol.Name}");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly {fullName} _native;");
        sb.AppendLine();
        sb.AppendLine($"    public {structSymbol.Name}({fullName} native) => _native = native;");
        sb.AppendLine($"    public static implicit operator {structSymbol.Name}({fullName} native) => new(native);");
        sb.AppendLine($"    public static implicit operator {fullName}({structSymbol.Name} wrapper) => wrapper._native;");
        sb.AppendLine();

        // 遍历结构体实例字段
        foreach (var field in structSymbol.GetMembers().OfType<IFieldSymbol>())
        {
            if (field.IsStatic) continue;

            var origName = field.Name;
            var pascName = ToPascalCaseName(origName);
            var fieldType = field.Type;

            // ======ban list======

            // SimaiTiming.Content 是一个指向解析内容的 String_View，不保证在 Wrapper 生命周期内有效。
            if (structSymbol.Name == "SimaiTiming" && pascName == "Content")
            {
                continue;
            }
            // 所有 Arena 都不应被 public
            else if (pascName == "Arena")
            {
                continue;
            }


            // ======special types======

            // Enum
            else if (fieldType.TypeKind == TypeKind.Enum)
            {
                var enumName = fieldType.Name;
                sb.AppendLine($"    public {enumName} {pascName} => ({enumName})_native.{origName};");
            }
            // xxxList
            else if (fieldType.Name.EndsWith("List"))
            {
                var elemType = fieldType.Name.Substring(0, fieldType.Name.Length - 4);

                // 使用 unsafe ReadOnlySpan 提取内部 items 指针与 count 计数
                sb.AppendLine($"    public unsafe ReadOnlySpan<{elemType}> {pascName} =>");
                sb.AppendLine($"        new(_native.{origName}.items, checked((int)_native.{origName}.count));");
            }
            // String_View
            else if (fieldType.Name == "String_View")
            {
                sb.AppendLine($"    public unsafe ReadOnlySpan<byte> {pascName} => ");
                sb.AppendLine($"        new(_native.{origName}.data, checked((int)_native.{origName}.count));");
            }
            // _Bool / bool
            else if (GetNativeType(field) is string nativeType && (nativeType == "_Bool" || nativeType == "bool"))
            {
                sb.AppendLine($"    public bool {pascName} => _native.{origName} != 0;");
            }


            // ======others======

            else
            {
                sb.AppendLine($"    public {fieldType.ToDisplayString()} {pascName} => _native.{origName};");
            }
        }

        sb.AppendLine("}");
        return (sb.ToString(), fixedBufferWrappers);
    }

    // 生成内联数组字段的包装类型 (放在外层 partial 文件，独立命名 <FieldName>Collection)。
    private static string GenerateFixedBufferWrapper(string containerTypeName, FixedBufferWrapper fb)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using Cimai.Native;");
        sb.AppendLine();
        sb.AppendLine("namespace Cimai;");
        sb.AppendLine();
        sb.AppendLine($"public readonly struct {fb.CollectionName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public const int Length = {fb.Length};");
        sb.AppendLine($"    private readonly {fb.FieldTypeFullName} _buffer;");
        sb.AppendLine($"    public {fb.CollectionName}({fb.FieldTypeFullName} buffer) => _buffer = buffer;");
        string ret = fb.ElemIsWrapper ? $"{fb.ElemWrapper}?" : fb.ElemType;
        sb.AppendLine($"    public unsafe {ret} this[int index]");
        sb.AppendLine("    {");
        sb.AppendLine("        get");
        sb.AppendLine("        {");
        sb.AppendLine("            if ((uint)index >= (uint)Length) return default;");
        sb.AppendLine("            var p = _buffer[index];");
        if (fb.ElemIsWrapper)
        {
            sb.AppendLine($"            return p == null ? null : new {fb.ElemWrapper}(*p);");
        }
        else
        {
            sb.AppendLine("            return p;");
        }
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private sealed class FixedBufferWrapper
    {
        public string CollectionName { get; }
        public string FieldTypeFullName { get; }
        public int Length { get; }
        public string ElemType { get; }
        public bool ElemIsWrapper { get; }
        public string ElemWrapper { get; }

        public FixedBufferWrapper(
            string CollectionName,
            string FieldTypeFullName,
            int Length,
            string ElemType,
            bool ElemIsWrapper,
            string ElemWrapper)
        {
            this.CollectionName = CollectionName;
            this.FieldTypeFullName = FieldTypeFullName;
            this.Length = Length;
            this.ElemType = ElemType;
            this.ElemIsWrapper = ElemIsWrapper;
            this.ElemWrapper = ElemWrapper;
        }
    }

    private static string ToPascalCaseName(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        if (NameMap.TryGetValue(name, out var mappedName)) return mappedName;

        var parts = name.Split(['_'], StringSplitOptions.RemoveEmptyEntries);
        for (int i = 0; i < parts.Length; i++)
        {
            if (parts[i].Length > 0)
                parts[i] = char.ToUpper(parts[i][0]) + parts[i].Substring(1);
        }
        return string.Concat(parts);
    }

    private static readonly Dictionary<string, string> NameMap = new()
    {
        { "hspeed", "HSpeed" },
        { "sveloc", "SVeloc" },
    };

    private static string GetNativeType(IFieldSymbol field)
    {
        foreach (var attr in field.GetAttributes())
        {
            if (attr.AttributeClass?.Name == "NativeTypeNameAttribute" ||
                attr.AttributeClass?.Name == "NativeTypeName")
            {
                if (attr.ConstructorArguments.Length > 0 &&
                    attr.ConstructorArguments[0].Value is string typeName)
                {
                    return typeName;
                }
            }
        }
        return string.Empty;
    }
}