using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Cimai.Generators;

[Generator]
public class NativeWrapperGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 所有属于 Cimai.Native 的类型定义
        IncrementalValuesProvider<INamedTypeSymbol> nativeSymbols = context.CompilationProvider
            .SelectMany(static (compilation, _) =>
            {
                var nativeNamespace = compilation.GlobalNamespace
                    .GetNamespaceMembers()
                    .FirstOrDefault(n => n.Name == "Cimai")
                    ?
                    .GetNamespaceMembers()
                    .FirstOrDefault(n => n.Name == "Native");

                if (nativeNamespace is null)
                    return Enumerable.Empty<INamedTypeSymbol>();

                return nativeNamespace.GetTypeMembers();
            });

        // 2. 注册源码生成输出
        context.RegisterSourceOutput(nativeSymbols, static (spc, symbol) =>
        {
            if (symbol is null)
                return;

            // ---- A. 处理 Enum：复制生成到 Cimai 命名空间下 ----
            if (symbol.TypeKind == TypeKind.Enum)
            {
                var enumCode = GenerateEnum(symbol);
                spc.AddSource($"{symbol.Name}.g.cs", enumCode);
                return;
            }

            // ---- B. 处理 Struct：仅针对 SimaiNote 和 SimaiTiming 生成 Wrapper ----
            if (symbol.TypeKind == TypeKind.Struct)
            {
                if (symbol.Name != "SimaiNote" && symbol.Name != "SimaiTiming")
                    return;

                var structCode = GenerateStructWrapper(symbol);
                spc.AddSource($"{symbol.Name}.g.cs", structCode);
            }
        });
    }

    // 生成 Enum 副本
    private static string GenerateEnum(INamedTypeSymbol enumSymbol)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("namespace Cimai;");
        sb.AppendLine();

        // 获取底层类型 (如 int, uint 等)
        var underlyingType = enumSymbol.EnumUnderlyingType?.ToDisplayString() ?? "int";
        sb.AppendLine($"public enum {enumSymbol.Name} : {underlyingType}");
        sb.AppendLine("{");

        // 遍历枚举的所有成员项及对应数值
        foreach (var member in enumSymbol.GetMembers().OfType<IFieldSymbol>())
        {
            if (member.HasConstantValue)
            {
                sb.AppendLine($"    {member.Name} = {member.ConstantValue},");
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // 生成 Struct 包装器
    private static string GenerateStructWrapper(INamedTypeSymbol structSymbol)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using Cimai.Native;");
        sb.AppendLine();
        sb.AppendLine("namespace Cimai;");
        sb.AppendLine();

        var fullName = structSymbol.ToDisplayString(); // 如 Cimai.Native.SimaiNote

        sb.AppendLine("[StructLayout(LayoutKind.Sequential)]");
        sb.AppendLine($"public readonly struct {structSymbol.Name}");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly {fullName} _native;");
        sb.AppendLine();
        sb.AppendLine($"    public {structSymbol.Name}({fullName} native) => _native = native;");
        sb.AppendLine($"    public static implicit operator {structSymbol.Name}({fullName} native) => new(native);");
        sb.AppendLine($"    public static implicit operator {fullName}({structSymbol.Name} wrapper) => wrapper._native;");
        sb.AppendLine();

        // 遍历结构体实例字段
        foreach (var field in structSymbol.GetMembers().OfType<IFieldSymbol>())
        {
            if (field.IsStatic) continue;

            var origName = field.Name;
            var pascName = ToPascalCase(origName);
            var fieldType = field.Type;

            // Enum
            if (fieldType.TypeKind == TypeKind.Enum)
            {
                var enumName = fieldType.Name;
                sb.AppendLine($"    public {enumName} {pascName} => ({enumName})_native.{origName};");
            }
            // xxxList
            else if (fieldType.Name.EndsWith("List"))
            {
                var elemType = fieldType.Name.Substring(0, fieldType.Name.Length - 4);

                // 使用 unsafe ReadOnlySpan 提取内部 items 指针与 count 计数
                sb.AppendLine($"    public unsafe ReadOnlySpan<{elemType}> {pascName} =>");
                sb.AppendLine($"        new(_native.{origName}.items, checked((int)_native.{origName}.count));");
            }
            // String_View
            else if (fieldType.Name == "String_View")
            {
                sb.AppendLine($"    public unsafe ReadOnlySpan<byte> {pascName} => ");
                sb.AppendLine($"        new(_native.{origName}.data, checked((int)_native.{origName}.count));");
            }
            // _Bool / bool
            else if (IsNativeBool(field))
            {
                sb.AppendLine($"    public bool {pascName} => _native.{origName} != 0;");
            }
            // others
            else
            {
                sb.AppendLine($"    public {fieldType.ToDisplayString()} {pascName} => _native.{origName};");
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        var parts = name.Split(['_'], StringSplitOptions.RemoveEmptyEntries);
        for (int i = 0; i < parts.Length; i++)
        {
            if (parts[i].Length > 0)
                parts[i] = char.ToUpper(parts[i][0]) + parts[i].Substring(1);
        }
        return string.Concat(parts);
    }

    private static bool IsNativeBool(IFieldSymbol field)
    {
        foreach (var attr in field.GetAttributes())
        {
            // 检查 Attribute 是否是 NativeTypeNameAttribute
            if (attr.AttributeClass?.Name == "NativeTypeNameAttribute" ||
                attr.AttributeClass?.Name == "NativeTypeName")
            {
                // 检查构造函数入参是不是 "_Bool" 或 "bool"
                if (attr.ConstructorArguments.Length > 0 &&
                    attr.ConstructorArguments[0].Value is string typeName)
                {
                    if (typeName == "_Bool" || typeName == "bool")
                        return true;
                }
            }
        }
        return false;
    }
}